/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const 'detect_platform': () => [number, number];
export const 'is_mobile': () => number;
export const run: (a: number, b: number) => any;
export const 'run_embed': (a: number, b: number, c: number, d: number) => any;
export const 'run_embed_nerf': (a: number, b: number, c: number, d: number, e: number) => any;
export const 'run_embed_scad': (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const 'run_embed_sdf': (a: number, b: number, c: number, d: number, e: number) => any;
export const 'run_embed_sdf_jsonld': (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const 'run_with_game': (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const 'run_with_graph': (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const 'run_with_sabiotoshi': (a: number, b: number, c: number, d: number) => any;
export const 'run_with_scene': (a: number, b: number, c: number, d: number) => any;
export const start: () => void;
export const 'wasm_bindgen__closure__destroy__h95a711ea1799e637': (a: number, b: number) => void;
export const 'wasm_bindgen__closure__destroy__h58248470da3c1778': (a: number, b: number) => void;
export const 'wasm_bindgen__closure__destroy__hdc06e97948d3d628': (a: number, b: number) => void;
export const 'wasm_bindgen__closure__destroy__h65a83ee28c491949': (a: number, b: number) => void;
export const 'wasm_bindgen__closure__destroy__h60a4caed9770f7f1': (a: number, b: number) => void;
export const 'wasm_bindgen__closure__destroy__h14efb445bdf2c435': (a: number, b: number) => void;
export const 'wasm_bindgen__closure__destroy__h50b91ea838929c49': (a: number, b: number) => void;
export const 'wasm_bindgen__closure__destroy__hf05eaf164083c114': (a: number, b: number) => void;
export const 'wasm_bindgen__convert__closures_____invoke__h4f3d1bb8ebec98d2': (a: number, b: number, c: any) => [number, number];
export const 'wasm_bindgen__convert__closures_____invoke__h07c5524e2faf0ff9': (a: number, b: number, c: any, d: any) => void;
export const 'wasm_bindgen__convert__closures_____invoke__h0d3c3e716750a55a': (a: number, b: number, c: any) => void;
export const 'wasm_bindgen__convert__closures_____invoke__hb6456330879e5c0c': (a: number, b: number, c: any) => void;
export const 'wasm_bindgen__convert__closures_____invoke__hb57275de00957bd7': (a: number, b: number, c: any) => void;
export const 'wasm_bindgen__convert__closures_____invoke__h6090315cfaf72934': (a: number, b: number, c: any) => void;
export const 'wasm_bindgen__convert__closures_____invoke__hc99e0d11a9e5ad83': (a: number, b: number, c: any) => void;
export const 'wasm_bindgen__convert__closures_____invoke__hab61f17cdeb776a7': (a: number, b: number, c: any) => void;
export const 'wasm_bindgen__convert__closures_____invoke__h3bbceb0bab7158be': (a: number, b: number) => number;
export const 'wasm_bindgen__convert__closures_____invoke__h067db1996cf8db1f': (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
